---
apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  selector:
    app: nodered
  type: NodePort
  ports:
  - name: dashboard
    port: 1880
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  selector:
    matchLabels:
      app: nodered
  serviceName: nodered
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: nodered-vol
    spec:
      accessModes:
      - ReadWriteOnce
      volumeMode: "Filesystem"
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        app: nodered
    spec:
      # Permissions to write in /data
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      # Node-RED Server
      containers:
      - name: nodered
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
          name: dashboard
        env:
        - name: TZ
          value: Europe/London
        volumeMounts:
        - name: nodered-vol
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /
            port: 1880
          initialDelaySeconds: 10
          timeoutSeconds: 5